name: CI

on:
  push:
    branches: [ master, main ]
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: maven

      - name: Install Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Install Xvfb (virtual display)
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb
          google-chrome --version

      - name: Run tests (under Xvfb)
        run: |
          xvfb-run -a -s "-screen 0 1920x1080x24" \
          mvn -B -Dfile.encoding=UTF-8 \
            -Dcucumber.plugin="io.qameta.allure.cucumber7jvm.AllureCucumber7Jvm,html:target/cucumber-report.html,json:target/cucumber.json,pretty" \
            -Dallure.results.directory=target/allure-results \
            clean test

      - name: Generate Allure HTML (CLI)
        uses: simple-elf/allure-report-action@v1
        with:
          allure_results: target/allure-results
          allure_report: target/allure-report
          keep_reports: 1

      - name: Upload reports (download from Actions → Artifacts)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: reports
          path: |
            target/allure-report
            target/cucumber-report.html
            target/cucumber.json
            target/surefire-reports
          retention-days: 7
