name: CI

on:
  push:
    branches: [ master, main ]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: maven

      - name: Install Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Install Xvfb (virtual display)
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb
          google-chrome --version

      - name: Run tests (under Xvfb)
        run: |
          xvfb-run -a -s "-screen 0 1920x1080x24" \
          mvn -B -Dfile.encoding=UTF-8 \
            -Dcucumber.plugin="io.qameta.allure.cucumber7jvm.AllureCucumber7Jvm,html:target/cucumber-report.html,json:target/cucumber.json,pretty" \
            -Dallure.results.directory=target/allure-results \
            clean test

      - name: Sanity check Allure results exist
        if: always()
        run: |
          echo "Listing target/allure-results"
          ls -la target/allure-results || true
          echo "Files in target:"
          ls -la target || true

      - name: Generate Allure HTML (CLI)
        if: always()
        uses: simple-elf/allure-report-action@v1
        with:
          allure_version: 2.24.0
          allure_results: target/allure-results
          allure_report: target/allure-report
          keep_reports: 1

      - name: Upload artifacts (download from Actions → Artifacts)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: reports
          path: |
            target/allure-report
            target/cucumber-report.html
            target/cucumber.json
            target/surefire-reports
          retention-days: 7

      - name: Create placeholder report if generation failed
        if: always()
        run: |
          if [ ! -f target/allure-report/index.html ]; then
            mkdir -p target/allure-report
            echo '<html><body><h2>No Allure results found.</h2></body></html>' > target/allure-report/index.html
          fi

      - name: Upload Allure report for Pages
        if: always()
        uses: actions/upload-pages-artifact@v3
        with:
          path: target/allure-report

  deploy-pages:
    if: always()
    needs: test
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
